### ISSUE TITLE
Parameter passing to cmdline

### ISSUE THREAD

**Issue by FranciscoHS** [aritoka/QiaOpt#17]
I was trying to run a very simple example using QiaOpt using the following code:

```
import os
import shutil
from qiaopt.pre import Experiment, SystemSetup, Parameter, OptimizationInfo
from qiaopt.run import Executor
from qiaopt.blueprint_tools import setup_optimization_dir


def rl_input():
    rl_experiment = Experiment(
        experiment_name="EntangleMaster",
        system_setup=SystemSetup(
            source_directory=os.getcwd(),
            program_name="entangle_master_runscript.py",
            command_line_arguments={"--n_coherence": 1.e+10,
                                    "--elementary_link_fidelity": 0.85},
            # analysis_script="analyse_function_output.py",
            executor="python",
            output_dir_name="output",
            venv="~/alt_rlquantumenv",
            num_nodes=2,
            alloc_time="01:00:00",
            slurm_args=["--exclusive"],
            modules=["2021", "Python/3.9.5-GCCcore-10.3.0"],
            output_extension="json"
        ),
        parameters=[
            Parameter(
                name="n_trials",
                param_range=[10, 10],
                constraints={'low': 10, 'high': 10},
                number_points=1,
                distribution="uniform",
                param_type="discrete",
            )
        ]
    )

    return rl_experiment


def remove_files_after_run():
    # remove files and directories
    dirs = [f for f in os.listdir(os.getcwd()) if (f.startswith(".qcg"))]
    for d in dirs:
        shutil.rmtree(os.path.join(os.getcwd(), d))


def main():
    def cost_function(f):
        return f

    experiment = rl_input()
    experiment.cost_function = cost_function
    rl_example = Executor(experiment=experiment)

    experiment.parse_slurm_arg('qiaopt_rl.py')

    rl_example.run(step=0)

    # clean up
    remove_files_after_run()


if __name__ == "__main__":
    main()
```

The idea is just to run the `entangle_master_runscript.py` with arguments --n_coherence 1.e+10 --elementary_link_fidelity 0.85 --n_trials 10.

However, what was actually being passed was:
--n_coherence 1.e+10 --elementary_link_fidelity 0.85 --n_trials '[10]'

The script could not interpret the value passed to --n_trials as an integer so an error was thrown (this is of course not hard to hack around by editing the script).

I believe I tracked the problem down to the following lines in the `qcgpilot_commandline` method of `run.py`:

```
            if len(experiment.parameters) == 1:
                # single parameter
                cmdline.append(datapoint_item)
            else:
                cmdline.append(datapoint_item[p])
```

If this is changed to simply `cmdline.append(datapoint_item[p])` (i.e., same behavior irrespective of the number of parameters) my use case is fixed. The problem seems to be that the method expected a float in case there was only one parameter, but this does not seem to be the case (there is a related TODO in the docstring, I see now).

I will push a small fix to a related PR. Let me know if I misinterpreted something.

Update: Apparently I don't have permission? Might just be doing something wrong on my side, not sure.

**Comment by dmark04** [comment]
Hey @FranciscoHS ,

thanks for pointing out this issue.

I executed the code snippet your provided and was able to reproduce your issue.
Your suggested change indeed fixes the issue for your snippet. However, to me it is a workaround for an issue that arises one step earlier: the `create_datapoint_c_product` function in `pre.py`

Thanks to your example I noticed that for a single parameter it also tries to perform a cartesian product resulting in a list of single entry tuples of the form `(x,)`. Or for your example `(10,)`.

Now, one could implement a change to `run.py` as you suggest. Then however, if a user decides while creating an experiment that: "oh hey I will write some of my own code and since I only have one parameter I don't need to call `create_datapoint_c_product`."
This will lead to this users `data_points` to be in a different structure (intuitively a list of the param values).

Therefore I think it is better to modify the `create_datapoint_c_product` function instead, such that for a single active parameter it does not attempt to form a cartesian product but just sets `experiment.data_points = param.data_points`.

This should fix your issue, while at the same time keeping `experiment.data_points` in a consistent and intuitive format no matter how the user wants to create it.

I created a branch for this issue and pushed the suggested change. Could you try it with your script `entangle_master_runscript.py` (which I don't have) and let me know if it indeed works now?

Also in principle you should very much be able to push to this repo, which branch did your try to push to? (main should be protected)

**Comment by FranciscoHS** [comment]
Hey @dmark04, thanks for the quick reply! Indeed your fix makes more sense, I was not familiar enough with the code to be aware of this. I'll try out your solution and let you know if it does it for my use case (but I believe it should).

I double-checked and indeed I was not pushing to main, but to a new branch. I think I just have something wrong with my github ssh configuration, so I need to sort that out.

**Comment by FranciscoHS** [comment]
Indeed does it for my use case (:

**Comment by dmark04** [comment]
Cool then I will merge the changes to master. Let me know if I can help you solve your github issue.
